# Next.js Documentation Optimization Profile
# Optimized for Next.js docs structure and content patterns

# File inclusion patterns
include:
  - "docs/**/*.md"
  - "docs/**/*.mdx"

# File exclusion patterns  
exclude:
  - "docs/api-reference/legacy/**"
  - "docs/pages/api-reference/legacy/**"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.min.*"

# Default topics for Next.js content
default_topics:
  - "framework"
  - "nextjs"
  - "react"
  - "web-development"
  - "javascript"
  - "typescript"

# Optimization profile for Next.js docs
profile: balanced

# Next.js specific transforms
transforms:
  # Handle Next.js specific MDX components
  mdx_components:
    - "Callout"
    - "Card"
    - "Cards"
    - "Tabs"
    - "Tab"
    - "Steps"
    - "FileTree"
  
  # Preserve important code examples but compress very large ones
  code_block_rules:
    preserve_languages:
      - "jsx"
      - "tsx" 
      - "javascript"
      - "typescript"
    max_lines: 30
    
  # Link rewriting rules for Next.js docs
  link_rules:
    base_url: "https://nextjs.org"
    preserve_anchors: true
