# React Documentation Optimization Profile
# Optimized for React docs structure and content patterns

# File inclusion patterns
include:
  - "docs/**/*.md"
  - "docs/**/*.mdx"
  - "beta/**/*.md"
  - "beta/**/*.mdx"

# File exclusion patterns
exclude:
  - "**/node_modules/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/.cache/**"
  - "**/*.min.*"
  - "**/legacy/**"

# Default topics for React content
default_topics:
  - "framework"
  - "react"
  - "javascript"
  - "ui"
  - "component"
  - "hooks"

# Optimization profile for React docs
profile: balanced

# React specific transforms
transforms:
  # Handle React docs specific MDX components
  mdx_components:
    - "Intro"
    - "YouWillLearn"
    - "Recap"
    - "Challenges"
    - "Hint"
    - "Solution"
    - "Sandpack"
    - "CodeStep"
    - "Diagram"
  
  # React examples are often crucial for understanding
  code_block_rules:
    preserve_languages:
      - "js"
      - "jsx"
      - "javascript"
      - "typescript"
      - "tsx"
    max_lines: 35
    
  # Link rewriting rules for React docs
  link_rules:
    base_url: "https://react.dev"
    preserve_anchors: true
