# Vite Documentation Optimization Profile
# Optimized for Vite docs structure and content patterns

# File inclusion patterns
include:
  - "docs/**/*.md"
  - "docs/**/*.mdx"

# File exclusion patterns
exclude:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.vite/**"
  - "**/*.min.*"

# Default topics for Vite content
default_topics:
  - "build-tool"
  - "vite"
  - "javascript"
  - "bundler"
  - "development"
  - "tooling"

# Optimization profile for build tool documentation
profile: balanced

# Vite specific transforms
transforms:
  # Vite docs use some custom components
  mdx_components:
    - "Details"
    - "Badge"
  
  # Build tool configs can be complex but important
  code_block_rules:
    preserve_languages:
      - "js"
      - "javascript"
      - "typescript"
      - "json"
      - "bash"
      - "shell"
    max_lines: 30
    
  # Link rewriting rules for Vite docs
  link_rules:
    base_url: "https://vitejs.dev"
    preserve_anchors: true
