# VS Code Documentation Optimization Profile
# Optimized for VS Code docs structure and content patterns

# File inclusion patterns
include:
  - "docs/**/*.md"
  - "api/**/*.md"

# File exclusion patterns
exclude:
  - "**/node_modules/**"
  - "**/out/**"
  - "**/dist/**" 
  - "**/.vscode/**"
  - "**/*.min.*"
  - "**/resources/**"

# Default topics for VS Code content
default_topics:
  - "editor"
  - "vscode"
  - "development-tools"
  - "ide"
  - "extensions"

# Optimization profile for editor documentation
profile: balanced

# VS Code specific transforms
transforms:
  # VS Code docs use minimal MDX components
  mdx_components: []
  
  # Configuration examples and API docs can be lengthy
  code_block_rules:
    preserve_languages:
      - "json"
      - "javascript"
      - "typescript"
      - "yaml"
      - "bash"
    max_lines: 40
    
  # Link rewriting rules for VS Code docs
  link_rules:
    base_url: "https://code.visualstudio.com"
    preserve_anchors: true
