# Contextor Optimization Configuration
# Copy this file to optimize.yaml and customize for your needs

# File inclusion patterns (glob patterns)
include:
  - "**/*.md"
  - "**/*.mdx"

# File exclusion patterns (glob patterns)
exclude:
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/__pycache__/**"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/CHANGELOG.md"
  - "**/LICENSE*"

# Default topics to apply to all files (can be overridden by CLI)
default_topics:
  - "documentation"

# Per-source configuration (optional)
sources:
  "vercel/next.js":
    topics:
      - "framework"
      - "nextjs"
      - "react"
    include:
      - "docs/**/*.md"
      - "docs/**/*.mdx"
    exclude:
      - "docs/api-reference/legacy/**"
  
  "tailwindlabs/tailwindcss":
    topics:
      - "css"
      - "framework"
      - "tailwind"
    include:
      - "src/**/*.md"
      - "src/**/*.mdx"

# Optimization profiles
profiles:
  lossless:
    # No content compression, preserve everything
    compress_code_blocks: false
    compress_json: false
    max_code_block_lines: null
    
  balanced:
    # Moderate compression for better token efficiency
    compress_code_blocks: true
    compress_json: true
    max_code_block_lines: 25
    
  compact:
    # Aggressive compression for maximum token savings
    compress_code_blocks: true
    compress_json: true
    max_code_block_lines: 15
    compress_whitespace: true
